image: atlassian/default-image:2

pipelines:
    tags:
      v*:
        - step:
           script:
             - git remote add sync git@github.com:miyabilink/sukkiri-java3-codes.git
             - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
             - git fetch origin
             - git checkout main
             - git pull
             - git merge origin/main
             - git filter-branch -f --env-filter "GIT_AUTHOR_NAME='Takuma SUGAWARA'; GIT_AUTHOR_EMAIL='sugawara@miyabilink.jp'; GIT_COMMITTER_NAME='Takuma SUGAWARA'; GIT_COMMITTER_EMAIL='sugawara@miyabilink.jp';" --tag-name-filter cat -- --all
             - git push sync --tags
             - git push -f sync main
